# Generated by Django 2.2.4 on 2020-04-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_from',
            field=models.DateField(verbose_name=('%d-%m-%Y', '%Y-%m-%d')),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_to',
            field=models.DateField(verbose_name=('%d-%m-%Y', '%Y-%m-%d')),
        ),
    ]
