# Generated by Django 2.2.4 on 2020-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0002_auto_20200426_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_to',
            field=models.DateField(),
        ),
    ]
