# Generated by Django 2.2.4 on 2020-04-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0003_auto_20200426_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='join',
            field=models.ManyToManyField(related_name='user_join', to='travel_buddy_app.User'),
        ),
    ]
